src/CoreMVC/Models/Context.cs
/**
 * Copyright 2016 IBM Corp. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the “License”);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an “AS IS” BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
using Microsoft.EntityFrameworkCore;
using Npgsql.EntityFrameworkCore.PostgreSQL;
using System.Linq;

namespace CoreMVC.Models
{
    public class Context : DbContext
    {
        public DbSet<Product> Products { get; set; }

        public Context(DbContextOptions<Context> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.HasPostgresExtension("uuid-ossp");
        }
       
    }
}

src/CoreMVC/Models/ElephantSQLCredentials.cs
/**
 * Copyright 2016 IBM Corp. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the “License”);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an “AS IS” BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace CoreMVC.Models
{
    public class ElephantSQLCredentials
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string Database { get; set; }
        public string Port { get; set; }
        public string Server { get; set; }
    }
}

src/CoreMVC/Models/Product.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMVC.Models
{
    public class Product
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [JsonProperty("_id")]
        public Guid Id { get; set; }
        [JsonProperty("name")]
        public string  Name{ get; set; }
        [JsonProperty("mark")]
        public string Mark { get; set; }

    }
}

src/CoreMVC/Controllers/HomeController.cs
/**
 * Copyright 2016 IBM Corp. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the “License”);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an “AS IS” BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
using Microsoft.AspNetCore.Mvc;
using CoreMVC.Models;

namespace CoreMVC.Controllers
{
    public class HomeController : Controller
    {
        private Context _context;

        public HomeController(Context context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/CoreMVC/Controllers/ProductController.cs
using CoreMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreMVC.Controllers
{
    public class ProductController : Controller
    {
        private Context _context;
        public ProductController(Context context)
        {
            _context = context;
        }

        public async Task<IActionResult> Create(Product p)
        {

            try
            {
                _context.Products.Add(p);
                await _context.SaveChangesAsync();

            }
            catch
            {

                ModelState.AddModelError("", "unable to add Product"
                );

            }
            return View();

        }
        public async Task<IActionResult> Show()
        {
            return View(await _context.Products.ToListAsync());
        }

    }
}

src/CoreMVC/Views/Home/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>ASP.NET Core ToDo Sample Application</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport"
          content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <environment names="Development">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="leftHalf">
        <img class="newappIcon" src="~/images/newapp-icon.png" />
        <h1>
            Welcome to the <span class="blue">ASP.NET ToDo Sample</span> on Bluemix!
        </h1>
        <p class="description">To get started see the Start Coding guide under your app in your dashboard.</p>
    </div>
    <div class="rightHalf">
        <div class="center">
            <header>
                <div class='title'>
                    ASP.NET ToDo Sample
                </div>
            </header>
            <table id='notes' class='records'><tbody></tbody></table>
            <div id="loading">&nbsp;&nbsp;Please wait while the data is being loaded...</div>
            <footer>
                <div class='tips'>
                    Click the Add button to add a record.
                    <button class='addBtn' onclick="addItem()" title='add record'>
                        <img src='~/images/add.png' alt='add' />
                    </button>
                </div>
            </footer>
            <environment names="Development">
                <script type="text/javascript" src="~/js/util.js"></script>
                <script type="text/javascript" src="~/js/index.js"></script>
            </environment>
            <environment names="Staging,Production">
                <script type="text/javascript" src="~/js/site.min.js" asp-append-version="true"></script>
            </environment>
        </div>
    </div>
</body>
</html>

src/CoreMVC/Views/Product/Create.cshtml
@model CoreMVC.Models.Product
@{
    ViewBag.Title = "Create";
}
@using (Html.BeginForm("Create", "Product", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">

        <h4>Create Product</h4>

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Mark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mark, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

    </div>

}
<div>
    @Html.ActionLink("Back to List", "Show")
</div>

src/CoreMVC/Views/Product/Show.cshtml
@model IEnumerable<CoreMVC.Models.Product>
@{
    ViewData["Title"] = "Index";
}
<h2>Products</h2>
<table class="table">
    <thead>
        <tr>
            <th>
                Mark
            </th>
            <th>
                Name
            </th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Mark)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
        </tr>
    }
</table>